### ISSUE TITLE
PPAify SRCFLib

### ISSUE THREAD

**Issue by doismellburning** [SRCF/SRCFLib#2]
My understanding is that current SRCF policy encourages installing Python dependencies from Ubuntu packages. In which case, could this be distributed via PPA please?

**Comment by doismellburning** [comment]
See https://github.com/SRCF/control-panel/pull/4

**Comment by rsa33** [comment]
This has now been done -- `python3-srcf` (which includes SRCFLib) is available from the [srcf/serveradmin](https://launchpad.net/~srcf/+archive/ubuntu/serveradmin) PPA.
